orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  install-yarn-example:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true

workflows:
  node-tests:
    jobs:
      - install-yarn-example
      - node/test
